FROM ubuntu:18.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y wget gnupg

RUN wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key| apt-key add -
RUN echo "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main" > /etc/apt/sources.list.d/llvm10.list

RUN apt-get update && apt-get install -y build-essential cmake ccache git-core gfortran libc++-dev

RUN apt-get update && apt-get install -y libtbb-dev libeigen3-dev libglew-dev libjpeg-dev libpng-dev openssh-client liblz4-dev libbz2-dev libboost-regex-dev libboost-filesystem-dev libboost-date-time-dev libboost-program-options-dev libopencv-dev libpython3-dev libgtest-dev libgoogle-glog-dev libatlas-base-dev libsuitesparse-dev

RUN apt-get update && apt-get install -y clang-10 clang-format
