FROM ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y wget gnupg

RUN apt-get update && apt-get install -y build-essential cmake ccache git-core gfortran libc++-dev

RUN apt-get update && apt-get install -y libtbb-dev libeigen3-dev libglew-dev libjpeg-dev libpng-dev openssh-client liblz4-dev libbz2-dev libboost-regex-dev libboost-filesystem-dev libboost-date-time-dev libboost-program-options-dev libopencv-dev libpython3-dev libgtest-dev libunwind-dev libgoogle-glog-dev libatlas-base-dev libsuitesparse-dev python3-distutils libfmt-dev

RUN apt-get update && apt-get install -y clang clang-format
